### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by hannesdelbeke** [hannesdelbeke/plugget#12]
believe this might be introduced with the upgrade command

pip has a admin issue with pyside module

```log
C:\Users\user>"C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\bin\\python.EXE" -m pip install --upgrade -r "C:/Users/user/AppData/Local/Temp/plugget/blender/halfsword-tools/latest/halfsword-tools/requirements.txt" -t "C:/Users/user/AppData/Roaming/Blender Foundation/Blender/3.2/scripts/modules" --no-user
Collecting buttonizer@ git+https://github.com/hannesdelbeke/buttonizer@main (from -r C:/Users/user/AppData/Local/Temp/plugget/blender/halfsword-tools/latest/halfsword-tools/requirements.txt (line 1))
  Cloning https://github.com/hannesdelbeke/buttonizer (to revision main) to c:\users\user\appdata\local\temp\pip-install-_xcuhykv\buttonizer_21888e12ff2b4c1c9fd7327d6d403bb5
  Running command git clone --filter=blob:none --quiet https://github.com/hannesdelbeke/buttonizer 'C:\Users\user\AppData\Local\Temp\pip-install-_xcuhykv\buttonizer_21888e12ff2b4c1c9fd7327d6d403bb5'
  Resolved https://github.com/hannesdelbeke/buttonizer to commit 618f4d51ea4e51edcdb9a81968ed3179c6cffc11
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting unimenu (from -r C:/Users/user/AppData/Local/Temp/plugget/blender/halfsword-tools/latest/halfsword-tools/requirements.txt (line 2))
  Using cached unimenu-3.0.0-py3-none-any.whl (17 kB)
Collecting pyyaml (from -r C:/Users/user/AppData/Local/Temp/plugget/blender/halfsword-tools/latest/halfsword-tools/requirements.txt (line 3))
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting PySide2 (from buttonizer@ git+https://github.com/hannesdelbeke/buttonizer@main->-r C:/Users/user/AppData/Local/Temp/plugget/blender/halfsword-tools/latest/halfsword-tools/requirements.txt (line 1))
  Using cached PySide2-5.15.2.1-5.15.2-cp35.cp36.cp37.cp38.cp39.cp310-none-win_amd64.whl (137.4 MB)
Collecting shiboken2==5.15.2.1 (from PySide2->buttonizer@ git+https://github.com/hannesdelbeke/buttonizer@main->-r C:/Users/user/AppData/Local/Temp/plugget/blender/halfsword-tools/latest/halfsword-tools/requirements.txt (line 1))
  Using cached shiboken2-5.15.2.1-5.15.2-cp35.cp36.cp37.cp38.cp39.cp310-none-win_amd64.whl (2.3 MB)
Building wheels for collected packages: buttonizer
  Building wheel for buttonizer (pyproject.toml) ... done
  Created wheel for buttonizer: filename=buttonizer-0.0.3-py3-none-any.whl size=4004 sha256=c309743233089ec60dc782ef69eff2beacf460cc0fc257bb09b298be9c440f5f
  Stored in directory: C:\Users\user\AppData\Local\Temp\pip-ephem-wheel-cache-kt4xdagv\wheels\0f\2a\07\69ec473eb266995e940eed99f2ea0abc029e14752f5145077b
Successfully built buttonizer
Installing collected packages: unimenu, shiboken2, pyyaml, PySide2, buttonizer
Successfully installed PySide2-5.15.2.1 buttonizer-0.0.3 pyyaml-6.0 shiboken2-5.15.2.1 unimenu-3.0.0

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pip\_internal\commands\install.py", line 507, in run
    self._handle_target_dir(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pip\_internal\commands\install.py", line 562, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\modules\\PySide2\\plugins\\imageformats\\qgif.dll'
```

**Comment by hannesdelbeke** [comment]
this issue is hidden atm since not all stuff from subprocess.run is passed to the blender console.
only found this when running manually.
results in confusion, since all we see is a `permission error`

**Comment by hannesdelbeke** [comment]
we ofcourse cant solve every package issue in plugget. but it should be clear why it fails.
TODO
print log output from subprocess

**Comment by hannesdelbeke** [comment]
- permission issue was caused by using `"` in `subprocess.run`
removing this removed it.
- also looked into console ouotput being passed to blender console, seems subprocess.run does this already by default on windows, and in realtime
