### ISSUE TITLE
bqt install error w plugget

### ISSUE THREAD

**Issue by hannesdelbeke** [hannesdelbeke/plugget#9]
instlal issue when installing bqt, on friends pc
![image](https://github.com/hannesdelbeke/plugget/assets/3758308/b34450dc-9df9-49b8-adfe-c5c7bf7e7bd4)

but files show in explorer. as if bqt installed successfully.
error seems to indicate attemp to install twice.
perhaps errored first time
![image](https://github.com/hannesdelbeke/plugget/assets/3758308/214b4fdb-7af2-4197-8883-7cdec9f85600)

bqt does not  show in blender
![image](https://github.com/hannesdelbeke/plugget/assets/3758308/0375f1d9-3a2d-4de3-871b-178304917655)

**Comment by hannesdelbeke** [comment]
plugget installed from blend file installer.
attempted to recreate on fresh blender, no plugget no bqt, but it didnt fail

**Comment by hannesdelbeke** [comment]
windows 11 
blender 3.5.1

**Comment by hannesdelbeke** [comment]
got error installing plugget in 3.5
```
Read blend: C:\Users\user\Downloads\install_plugget_addon.blend
Error: Python: Traceback (most recent call last):
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\python\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp_o2_dffp\\plugget-blender-addon-main\\plugget_addon.py' -> 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\plugget_addon.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\install_plugget_addon.blend\auto install Plugget Add-on", line 25, in <module>
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\python\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\python\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\python\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\plugget_addon.py'
```

**Comment by hannesdelbeke** [comment]
seems separate issue.
first time we run. addon folder doesnt yet exist
adding this to blend installer fixes it
```python
local_addons_dir.mkdir(exist_ok=True, parents=True)
```

**Comment by hannesdelbeke** [comment]
still getting
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\user\Downloads\install_plugget_addon.blend\auto install Plugget Add-on", line 35, in <module>
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'plugget_addon'
```

**Comment by hannesdelbeke** [comment]
on blender 3.5 clean install i get error 

```
WARNING:root:Failed to enable plugin 'bqt'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\modules\plugget\actions\blender_addon.py", line 33, in _enable_addons
    bpy.ops.preferences.addon_enable(module=addon_name)
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\user\Downloads\Blender_Launcher_v1.15.0_Windows_x64\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\bqt\__init__.py", line 12, in <module>
    import PySide2.QtCore as QtCore
ModuleNotFoundError: No module named 'PySide2'
```

seems dependencies are not installed nicely

**Comment by hannesdelbeke** [comment]
error says 
```
requirements.txt found, installing requirements
ERROR: Can not combine '--user' and '--target'
```

pyside2 is in bqt's requirements.txt. seems some command issue

**Comment by hannesdelbeke** [comment]
install of bqt fails, because bqt addon is already installed.
however bqt doesnt show up in bnlender addons, because dependencies are missing so it never imports.
so if we check if bqt is in addons, and if not install.  this wont work

**Comment by hannesdelbeke** [comment]
dependencies now install before main package, fixing this bug
